server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: http://employee-service:8080        
        predicates:
        - Path=/api/employee/**
        filters:
        - AuthenticationFilter

      - id: login-service
        uri: http://login-service:8090         
        predicates:
        - Path=/api/login/**
        filters:
        - AuthenticationFilter

        
eureka:
      client:
        register-with-eureka: true
        fetch-registry: true


#application:
#      security:
#        jwt:
#          secret-key:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
